Remove use of GetOutputAddresses
Sometimes this error would appear:

```
NoMethodError: undefined method `output_addresses'
```

Perhaps because of the way we have a light service action that
was also an organizer